# Generated by Django 4.0.4 on 2022-12-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='albumes.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='n_album',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre del album'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='ruta_foto',
            field=models.FileField(null=True, upload_to='fotos/'),
        ),
    ]
