# Generated by Django 4.0.4 on 2023-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumes', '0002_foto_album_alter_album_n_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='n_foto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombre foto'),
        ),
    ]
