# Generated by Django 4.0.4 on 2022-11-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clas_ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_clas', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='clasificacion de ubicacion')),
            ],
            options={
                'verbose_name': 'clasificacion',
                'verbose_name_plural': 'clasificaciones',
                'ordering': ['id'],
            },
        ),
    ]
