# Generated by Django 4.0.4 on 2022-11-17 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_ubicacion', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='clasificacion de ubicacion')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='direccion')),
                ('latitud', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='latitud')),
                ('longitud', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='longitud')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.clas_ubicacion')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['id'],
            },
        ),
    ]
