# Generated by Django 4.0.4 on 2022-11-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_alter_ubicacion_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='latitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='n_ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='nombre de ubicacion'),
        ),
    ]
