# Generated by Django 4.0.4 on 2022-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_alter_ubicacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='direccion'),
        ),
    ]
