# Generated by Django 4.0.4 on 2022-12-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_alter_ubicacion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas_ubicacion',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='color del marcador'),
        ),
        migrations.AddField(
            model_name='clas_ubicacion',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='icono del marcador'),
        ),
    ]
