# Generated by Django 4.0.4 on 2022-12-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapa', '0006_clas_ubicacion_color_clas_ubicacion_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(blank=True, max_length=150, null=True, verbose_name='comentario')),
                ('puntaje', models.CharField(blank=True, choices=[('1', 'MALO'), ('2', 'MODESTO'), ('3', 'COMUN'), ('4', 'BUENO'), ('5', 'PERFECTO')], default=3, max_length=1, null=True, verbose_name='puntaje')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapa.ubicacion')),
            ],
        ),
    ]
