# Generated by Django 4.0.4 on 2023-03-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0008_alter_ubicacion_autorizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='puntaje',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=3, null=True, verbose_name='puntaje'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='estado'),
        ),
    ]
