# Generated by Django 4.0.4 on 2023-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0009_alter_comentario_puntaje_alter_ubicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='puntaje',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='puntaje'),
        ),
    ]
