# Generated by Django 4.0.4 on 2022-05-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_gen', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='genero')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_pais', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='pais de origen')),
            ],
            options={
                'verbose_name': 'pais de origen',
                'verbose_name_plural': 'paises de origen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_rol', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='rol')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=150, null=True, unique=True, verbose_name='email del usuario')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombres', models.CharField(max_length=150, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=150, null=True, verbose_name='apellidos')),
                ('estado', models.BooleanField(default=True)),
                ('u_admin', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.genero')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.pais')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.rol')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['id'],
            },
        ),
    ]
