# Generated by Django 4.0.4 on 2022-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_estado_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(default='h', max_length=1, null=True, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='nombres'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
