# Generated by Django 4.0.4 on 2022-12-09 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapa', '0005_alter_ubicacion_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='paseo_v',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='ingrese la url', max_length=512, verbose_name='url')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mapa.ubicacion')),
            ],
            options={
                'verbose_name': 'paseo virtual',
                'verbose_name_plural': 'paseos virtuales',
                'ordering': ['id'],
            },
        ),
    ]
