# Generated by Django 4.0.4 on 2022-12-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_clas_ubicacion_color_clas_ubicacion_icono'),
        ('paseosv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseo_v',
            name='ubicacion',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='mapa.ubicacion'),
        ),
    ]
